SCREEN_WIDTH = 500
SCREEN_HEIGHT = 400

WALL_WIDTH = 5
WALL_SIZES = 4
WALL_LENGTH = 40
WALL_MAX_LENGTH = WALL_LENGTH * WALL_SIZES
INIT_WALL_NUM = 7
WALL_SPAWN_RATE = 1.5

PLAYER_SIZE = 15
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 150

FLAG_WIDTH = 10
FLAG_HEIGHT = 20
FLAG_SPEED = 75
SAFE_DISTANCE = 75

TIMER_START = 20
