SCREEN_WIDTH = 750
SCREEN_HEIGHT = 500

WALL_WIDTH = 5
WALL_SIZES = 4
WALL_LENGTH = 40
WALL_MAX_LENGTH = WALL_LENGTH * WALL_SIZES
INIT_WALL_NUM = 10
WALL_SPAWN_RATE = 1.5

PLAYER_SIZE = 15
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 150

FLAG_WIDTH = 15
FLAG_HEIGHT = 30
FLAG_SPEED = 75
SAFE_DISTANCE = 75

TIMER_START = 30
