SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000

WALL_WIDTH = 2
WALL_SIZES = 4
WALL_LENGTH = 20
WALL_MAX_LENGTH = WALL_LENGTH * WALL_SIZES

PLAYER_SIZE = 15
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 150

FLAG_WIDTH = 10
FLAG_LENGTH = 20

